[package]
name = "mpg123-sys"
version = "0.0.1"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
build = "build.rs"
links = "mpg123"

[dependencies]
libc = "0.2"

[build-dependencies]
pkg-config = "0.3"
